//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingEcart2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class AdminUser
    {
        public int AdminId { get; set; }
        [Required(ErrorMessage = "Please enter username ")]
        [DisplayName("Username")]
        public string AdminUsername { get; set; }
        [Required(ErrorMessage = "Please enter Password ")]
        [DataType(DataType.Password)]
        [DisplayName("Password")]
        public string AdminPassword { get; set; }
        [DataType(DataType.Password)]
        [DisplayName("Confirm Password")]
        [Compare("AdminPassword")]
        [Required(ErrorMessage = "Please enter Confirm Password ")]
        public string ConfirmPassword { get; set; }
        public string Email { get; set; }
        [Required(ErrorMessage = "Please enter Firstname ")]
        public string FirstName { get; set; }
        [Required(ErrorMessage = "Please enter Lastname ")]
        public string LastName { get; set; }
        public Nullable<bool> IsAdmin { get; set; }
        public string AdminLoginErrorMessage { get; set; }
    }
}
